//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicHeuristicAlgorithm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public decimal MaximalRecursionDepth {
            get {
                return ((decimal)(this["MaximalRecursionDepth"]));
            }
            set {
                this["MaximalRecursionDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenSquaresBonusHeuristic {
            get {
                return ((bool)(this["OpenSquaresBonusHeuristic"]));
            }
            set {
                this["OpenSquaresBonusHeuristic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal OpenSquaresBonusHeuristicWeight {
            get {
                return ((decimal)(this["OpenSquaresBonusHeuristicWeight"]));
            }
            set {
                this["OpenSquaresBonusHeuristicWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LargeValuesOnEdgeHeuristic {
            get {
                return ((bool)(this["LargeValuesOnEdgeHeuristic"]));
            }
            set {
                this["LargeValuesOnEdgeHeuristic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal LargeValuesOnEdgeHeuristicWeight {
            get {
                return ((decimal)(this["LargeValuesOnEdgeHeuristicWeight"]));
            }
            set {
                this["LargeValuesOnEdgeHeuristicWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NonMonotonicLinesPenaltyHeuristic {
            get {
                return ((bool)(this["NonMonotonicLinesPenaltyHeuristic"]));
            }
            set {
                this["NonMonotonicLinesPenaltyHeuristic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal NonMonotonicLinesPenaltyHeuristicWeight {
            get {
                return ((decimal)(this["NonMonotonicLinesPenaltyHeuristicWeight"]));
            }
            set {
                this["NonMonotonicLinesPenaltyHeuristicWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NumberOfMergesHeuristic {
            get {
                return ((bool)(this["NumberOfMergesHeuristic"]));
            }
            set {
                this["NumberOfMergesHeuristic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal NumberOfMergesHeuristicWeight {
            get {
                return ((decimal)(this["NumberOfMergesHeuristicWeight"]));
            }
            set {
                this["NumberOfMergesHeuristicWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal NumberOfRuns {
            get {
                return ((decimal)(this["NumberOfRuns"]));
            }
            set {
                this["NumberOfRuns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveStatistics {
            get {
                return ((bool)(this["SaveStatistics"]));
            }
            set {
                this["SaveStatistics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TicTacToeAutomaticMoves {
            get {
                return ((bool)(this["TicTacToeAutomaticMoves"]));
            }
            set {
                this["TicTacToeAutomaticMoves"] = value;
            }
        }
    }
}
